// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicEFApp;

#nullable disable

namespace MusicEFApp.Migrations
{
    [DbContext(typeof(MusicDBContext))]
    partial class MusicDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicEFApp.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlbumId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            Name = "StarTrek"
                        },
                        new
                        {
                            AlbumId = 2,
                            Name = "Medows"
                        },
                        new
                        {
                            AlbumId = 3,
                            Name = "Peaches"
                        },
                        new
                        {
                            AlbumId = 4,
                            Name = "Shallows"
                        });
                });

            modelBuilder.Entity("MusicEFApp.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongId"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SongId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            AlbumId = 1,
                            Title = "hello all"
                        },
                        new
                        {
                            SongId = 2,
                            AlbumId = 1,
                            Title = "Neither I"
                        },
                        new
                        {
                            SongId = 3,
                            AlbumId = 1,
                            Title = "Let it go"
                        },
                        new
                        {
                            SongId = 4,
                            AlbumId = 2,
                            Title = "song 1"
                        },
                        new
                        {
                            SongId = 5,
                            AlbumId = 2,
                            Title = "song 2"
                        },
                        new
                        {
                            SongId = 6,
                            AlbumId = 2,
                            Title = "song 3"
                        });
                });

            modelBuilder.Entity("MusicEFApp.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            EmailId = "Admin@gmail.com",
                            Name = "VJ",
                            Password = "Admin@123",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            EmailId = "user@gmail.com",
                            Name = "user",
                            Password = "user@123",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("MusicEFApp.Song", b =>
                {
                    b.HasOne("MusicEFApp.Album", "Album")
                        .WithMany("Song")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MusicEFApp.Album", b =>
                {
                    b.Navigation("Song");
                });
#pragma warning restore 612, 618
        }
    }
}
